title: The AI Bookshelf # The title of the blog
author: Volkan Cirik # Your name 
email: vcirik@cs.cmu.edu # your email shown in the footer
url: http://theaibookshelf.com # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Book reviews related to Artificial Intelligence.
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage

# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://www.cs.cmu.edu/~vcirik/assets/img/prof_pic.jpg" # avatar in about page
  about_you: a PhD student at Carnegie Mellon University working on language grounding. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "The Shelf" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: volkancirik
    github:  volkancirik
    rss: RSS
    # dribbble: 
    #facebook: huangyz0918
    # flickr:   
    # instagram: 
    # linkedin: yizheng-huang
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
remote_theme: huangyz0918/moving # note, please use volkancirik/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
